### ISSUE TITLE
Security Vulnerabilities in Python Chat Application - Action Required  🚨

### ISSUE THREAD

**Issue by nflatrea** [HalilDeniz/CryptoChat#7]
Hey @HalilDeniz !

I would like to bring to your attention some critical security concerns discovered in the current implementation of your Python chat application. It has come to my notice that the application, while claiming end-to-end encryption, decrypts messages on the server side, introducing potential vulnerabilities. This compromises the privacy and security assurances that end-to-end encryption is designed to provide. The following points highlight key areas of concern and suggested improvements.

Hope it'll help ! Good luck !

b35363

---

### False End-to-End Encryption Claims

Decrypting messages on the server undermines the purpose of end-to-end encryption, making it vulnerable to unauthorized access. Messages should only be decrypted on the client side.

```python
try:
    encrypted_message = self.client_socket.recv(1024)
    message = cipher.decrypt(encrypted_message).decode('utf-8') # this is a big NO-NO !
    # ...
except:
    pass
```

**Problem**: The application falsely claims end-to-end encryption, but messages are decrypted on the server side, compromising the integrity of the encryption model.

**Recommendation**:
- Avoid decrypting messages on the server to maintain true end-to-end encryption. Messages should only be decrypted on the client side. You should separate encrypted message payloads and remote procedure calls and metadata.
- Catching a broad except without specific exceptions makes debugging difficult. It's recommended to catch specific exceptions and log detailed error messages.

### Insecure Key Derivation:

```python
password = args.key.encode()
key = hashlib.sha256(password).digest()  # technically a good idea, but not that secure -_-
fernet_key = base64.urlsafe_b64encode(key)
cipher = Fernet(fernet_key)
```

**Problem**:
The encryption key is derived using a simple SHA-256 hash of the password, which is not considered as a secure key derivation.

**Recommendation**: 
- Implement a well-known Key Derivation Function (KDF) for secure key derivation. This enhances the overall security of the application. You could use sha-256 Based key derivation (HKDF-SHA-256) or Password Based Key Derivation (PBKDF)

### Secure Key Management:

```bash
$ python3 serverE.py --key Pa$$word123
```

**Problem**: The password is exposed as a command-line argument, posing a security risk.

**Recommendation**: Prompt the user for sensitive information like passwords to prevent exposure in command-line history. Consider using key files or environment variables for better key management.

**Comment by HalilDeniz** [comment]
Hello.
First of all, thank you for your feedback.
I will start working on this issue as soon as possible. In the meantime, I would like to ask you, if you have time, to update the program and send it to me with a pull request.
I would like to point out that the CryptoChat application grows with your support.
I thank you again and express my regards.

**Comment by nflatrea** [comment]
Of course ! Whenever I have time

**Comment by HalilDeniz** [comment]
that would be amazing, can you reach me on the: https://www.linkedin.com/in/halil-ibrahim-deniz/
